name: Android CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
         name: apk
         path: androidApp/build/outputs/apk/debug/**.apk
          
  build-iOs:
   
   runs-on: macos-latest
   steps:
   - uses: actions/checkout@v2
   - name: Select Xcode
     run: sudo Xcode-select -switch /Applications/Xcode_13.2.1.app
   - name: Build & Test 
     run: xcodebuild clean build test -workspace ProjectName.xcworkspace -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.2'
